-- Databricks notebook source
-- MAGIC %sql
-- MAGIC CREATE OR REPLACE TABLE
-- MAGIC   table2 (
-- MAGIC     artist_id STRING,
-- MAGIC     artist_name STRING,
-- MAGIC     duration DOUBLE,
-- MAGIC     release STRING,
-- MAGIC     tempo DOUBLE,
-- MAGIC     time_signature DOUBLE,
-- MAGIC     title STRING,
-- MAGIC     year DOUBLE,
-- MAGIC     processed_time TIMESTAMP
-- MAGIC   );
-- MAGIC
-- MAGIC INSERT INTO
-- MAGIC   table2
-- MAGIC SELECT
-- MAGIC   artist_id,
-- MAGIC   artist_name,
-- MAGIC   duration,
-- MAGIC   release,
-- MAGIC   tempo,
-- MAGIC   time_signature,
-- MAGIC   title,
-- MAGIC   year,
-- MAGIC   current_timestamp()
-- MAGIC FROM
-- MAGIC   table1
